services:
  app:
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./src
        target: /app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
  db:
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: db-volume
        target: /var/lib/postgresql/data
      - type: bind
        source: ./docker/db/init
        target: /docker-entrypoint-initdb.d
    image: postgres:17
volumes:
  db-volume:
