# Generated by Django 5.2 on 2026-03-26 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='プロジェクト名')),
                ('version_count', models.IntegerField(default=0, verbose_name='履歴数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_no', models.IntegerField(verbose_name='履歴番号')),
                ('file', models.FileField(upload_to='latex/')),
                ('original_text', models.TextField()),
                ('advice_text', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='reviewer.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name_plural': 'History',
            },
        ),
    ]
