# Generated by Django 5.2 on 2026-03-27 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='プロジェクトID')),
                ('title', models.TextField(max_length=100, verbose_name='プロジェクト名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='latex/', verbose_name='Latexファイル')),
                ('original_text', models.TextField(verbose_name='Latex内テキスト')),
                ('advice_text', models.TextField(verbose_name='アドバイステキスト')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='reviewer.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name_plural': 'History',
            },
        ),
    ]
