# Generated by Django 5.2 on 2026-03-26 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='advice_text',
            field=models.TextField(verbose_name='アドバイステキスト'),
        ),
        migrations.AlterField(
            model_name='history',
            name='file',
            field=models.FileField(upload_to='latex/', verbose_name='Latexファイル'),
        ),
        migrations.AlterField(
            model_name='history',
            name='original_text',
            field=models.TextField(verbose_name='Latex内テキスト'),
        ),
    ]
