# Generated by Django 5.2 on 2026-03-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history_no',
            field=models.IntegerField(default=0, verbose_name='履歴番号'),
            preserve_default=False,
        ),
    ]
