# Generated by Django 5.2 on 2026-03-26 10:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_project_created_at_alter_history_advice_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='history_no',
        ),
        migrations.RemoveField(
            model_name='project',
            name='version_count',
        ),
        migrations.AddField(
            model_name='history',
            name='history_id',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='履歴ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='プロジェクトID'),
        ),
    ]
